development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Mongoid can connect to a URI accepted by the driver:
       uri: mongodb+srv://techniquea2z:Taicho1337-@mysmsmessenger.utilj7k.mongodb.net/?retryWrites=true&w=majority&appName=MySMSMessenger/my_sms_messenger_db
  # Configure Mongoid-specific options. (optional)
  options:

  # Configure Driver-specific options. (optional)
  driver_options:


production:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Mongoid can connect to a URI accepted by the driver:
      uri: mongodb+srv://techniquea2z:Taicho1337-@cluster0.2hewar.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  # Configure Mongoid-specific options. (optional)
  options:

  # Configure Driver-specific options. (optional)
  driver_options:



test:
  clients:
    default:
      database: my_sms_messenger_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
